import { useEffect, useState } from 'react';
import { Link, NavLink, useNavigate } from 'react-router-dom';
import { ArrowUpRight, Search, Plus, Wallet, Menu, X, ArrowRight, CircleHelp } from 'lucide-react';
import { toast } from 'sonner';
import { api, short } from '../lib/api';
import { Btn, Modal, Field, ErrorBox } from './Kit';
import { useWallet } from './WalletContext';
import { FooterInformation } from './information/FooterInformation';

export const Brand = () => <span className="brand">MART<span className="brand-mark"><i /><i /><i /></span></span>;
export const Header = () => {
  const [menu, setMenu] = useState(false), [add, setAdd] = useState(false), [address, setAddress] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [search, setSearch] = useState('');
  const { wallet, openWallet } = useWallet(); const navigate = useNavigate();
  useEffect(() => { const showAddToken = () => { setError(''); setAdd(true); }; window.addEventListener('mart:open-add-token', showAddToken); return () => window.removeEventListener('mart:open-add-token', showAddToken); }, []);
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { const result = await api('/tokens', { method: 'POST', body: { address: address.trim() } }); setAdd(false); setAddress(''); navigate(`/token/${result.token.address}/market`); toast.success(result.created ? 'Your Token Hub is ready. Adding a token does not grant ownership.' : 'This token already has a Hub. Welcome back.'); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  return <><header className="header"><div className="nav-inner"><Link to="/" data-testid="brand-home" aria-label="MART home"><Brand /></Link><nav className="desktop-nav"><NavLink to="/explore" data-testid="nav-explore">Explore</NavLink><NavLink to="/events" data-testid="nav-events">Events</NavLink><NavLink to="/launch" data-testid="nav-launch">Launch<ArrowUpRight size={13} /></NavLink></nav><form className="nav-search" onSubmit={e => { e.preventDefault(); navigate(`/explore?q=${encodeURIComponent(search)}`); }}><Search size={16} /><input placeholder="Search tokens or address" value={search} onChange={e => setSearch(e.target.value)} data-testid="nav-search-input" aria-label="Search tokens" /><kbd>/</kbd></form><div className="nav-actions"><button className="add-token-link" data-testid="add-token-button" onClick={() => { setError(''); setAdd(true); }}><Plus size={15} />Add Token</button><Btn data-testid="connect-wallet-button" onClick={wallet ? () => navigate('/wallet') : openWallet}><Wallet size={16} /><span>{wallet ? short(wallet) : 'Connect Wallet'}</span></Btn><button className="mobile-menu" aria-label="Toggle navigation" data-testid="mobile-menu-toggle" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div></div>{menu && <nav className="mobile-navigation">{[['Explore', '/explore'], ['Events', '/events'], ['Launch Token', '/launch'], ['My Wallet', '/wallet']].map(([label, path]) => <Link key={path} to={path} data-testid={`mobile-${label.toLowerCase().replaceAll(' ', '-')}`} onClick={() => setMenu(false)}>{label}<ArrowUpRight size={16} /></Link>)}<button data-testid="mobile-add-token" onClick={() => { setMenu(false); setError(''); setAdd(true); }}>+ Add Token</button></nav>}</header>
    <Modal open={add} onClose={() => setAdd(false)} title="Every token deserves a market." description="Add an existing Solana token. One address. One Token Hub." id="add-token"><form className="form-stack" onSubmit={submit}><Field label="Solana token address" id="token-address-input" required value={address} onChange={e => setAddress(e.target.value)} placeholder="Paste the token mint address" /><div className="info-note"><CircleHelp size={18} /><p>Token details are verified on Solana. Existing Hubs open automatically. New Hubs start unclaimed.</p></div><ErrorBox error={error} /><Btn data-testid="add-token-submit" busy={busy} type="submit">{busy ? 'Finding your token…' : 'Find & open Token Hub'}<ArrowRight size={16} /></Btn></form></Modal>
  </>;
};
export const Footer = () => <footer className="footer"><div className="footer-main"><div><Link to="/" data-testid="footer-brand"><Brand /></Link><p>A market built around every token.</p></div><div className="footer-links"><Link to="/explore" data-testid="footer-explore">Explore tokens</Link><Link to="/events" data-testid="footer-events">Events</Link><Link to="/launch" data-testid="footer-launch">Launch a token<ArrowUpRight size={13} /></Link></div><span className="solana-powered"><span className="solana-mark">≋</span> Built on Solana</span></div><FooterInformation /><div className="footer-bottom"><span>© 2026 MART. Your token. Your ecosystem.</span><span>Non-custodial by design.<span className="live-dot" /></span></div></footer>;