import { Link } from 'react-router-dom';
import { BarChart3, Cpu, Wallet, ArrowUpRight, LockKeyhole } from 'lucide-react';
import { useData } from '../../lib/api';
import { External } from '../Kit';
import { AgentProfileSummary } from './AgentProfileSummary';
import { CAPABILITIES, ALLOCATIONS } from './agentData';
import { TokenPriceChart } from './TokenPriceChart';

export const HubOverview = ({ token }) => {
  const { data: agent, loading, error, reload } = useData(`/tokens/${token.address}/agent`);
  return <section className="token-overview" data-testid="hub-integrated-overview">
    <div className="token-overview-grid">
      {loading ? <div className="token-agent-summary token-panel-loading" data-testid="hub-agent-loading">Loading agent profile…</div> : error ? <div className="token-agent-summary token-panel-loading" role="alert" data-testid="hub-agent-error"><p>{error}</p><button className="text-link" data-testid="hub-agent-retry" onClick={reload}>Retry agent profile</button></div> : <AgentProfileSummary agent={agent} />}
      <div className="token-chart-section" data-testid="hub-chart-container"><div className="token-panel-title"><span><BarChart3 size={15} /> PRICE CHART</span><External id="hub-overview-chart-link" href={token.dex_url}>Open chart</External></div><TokenPriceChart token={token} /><div className="token-chart-summary"><span data-testid="hub-chart-source">24H change · DexScreener snapshot</span><span data-testid="hub-chart-change" className={token.change >= 0 ? 'positive' : 'negative'}>{token.change == null ? '—' : `${token.change >= 0 ? '+' : ''}${token.change.toFixed(2)}%`} <small>24H</small></span></div><div className="token-trade-actions"><External href={token.pump_url} className="btn btn-primary" id="hub-overview-buy">Buy ${token.symbol}<ArrowUpRight size={13} /></External><External href={token.pump_url} className="btn btn-secondary" id="hub-overview-sell">Sell ${token.symbol}</External><span data-testid="hub-chart-disclaimer">Public price history, not a streaming execution price.</span></div></div>
      <aside className="token-resources"><section className="token-compute-panel" data-testid="hub-compute-panel"><div className="token-panel-title"><span><Cpu size={15} /> COMPUTE</span><small data-testid="hub-compute-status">NOT CONNECTED</small></div><div className="token-compute-credit"><strong data-testid="hub-compute-credits">— <small>USD credits</small></strong><span>No compute account linked</span></div><div className="token-compute-metrics"><span>Usage <strong data-testid="hub-compute-usage">—</strong></span><span>Agent runs <strong data-testid="hub-compute-runs">0</strong></span></div><Link to="/docs/agent-compute" data-testid="hub-compute-guide" className="text-link">Compute roadmap<ArrowUpRight size={12} /></Link></section>
        <section className="token-treasury-panel" data-testid="hub-treasury-panel"><div className="token-panel-title"><span><Wallet size={15} /> AGENT TREASURY</span></div><div className="token-treasury-line"><span>SOL</span><strong data-testid="hub-treasury-sol">—</strong></div><div className="token-treasury-line"><span>${token.symbol}</span><strong data-testid="hub-treasury-token">—</strong></div><p data-testid="hub-treasury-status">No agent treasury linked.</p>{agent?.profile && <><span className="token-panel-eyebrow">PROPOSED ALLOCATION</span><div className="token-allocation-bar" data-testid="hub-allocation-bar">{ALLOCATIONS.map(a => <span key={a.id} style={{ width: `${agent.profile.allocation[a.id]}%`, background: a.color }} />)}</div>{ALLOCATIONS.map(a => <div className="token-allocation-row" key={a.id} data-testid={`hub-allocation-${a.id}`}><i style={{ background: a.color }} /><span>{a.name}</span><strong>{agent.profile.allocation[a.id]}%</strong></div>)}</>}<span className="token-panel-footnote"><LockKeyhole size={11} />No automated transfers</span></section>
      </aside>
    </div>
    <div className="token-overview-bottom"><div className="token-operating-loop" data-testid="hub-agent-capabilities"><span className="token-panel-eyebrow">{agent?.profile ? 'PLANNED CAPABILITIES' : 'AGENT CAPABILITIES · OPTIONAL'}</span><div>{CAPABILITIES.map(c => <span key={c.id} data-testid={`hub-capability-${c.id}`} className={agent?.profile?.capabilities.includes(c.id) ? 'configured' : ''}><c.icon size={14} />{c.name}</span>)}</div></div><div className="token-ecosystem-counts" data-testid="hub-ecosystem-counts">{[['listings', 'Market listings'], ['events', 'Events'], ['posts', 'Community posts']].map(([key, label]) => <div key={key}><strong data-testid={`hub-count-${key}`}>{agent ? agent.ecosystem[key] : '—'}</strong><span>{label}</span></div>)}</div></div>
  </section>;
};